name: E2E Tests

on:
  workflow_dispatch:
  push:
    branches: [ master, main ]
  pull_request:
    branches: [ master, main ]
  schedule:
    # Run weekly on Sundays at 3 AM UTC
    - cron: '0 3 * * 0'

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  e2e-test:
    runs-on: ${{ matrix.os }}
    name: E2E Tool Installation and ArduPilot Build (${{ matrix.os }})
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest]

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22'
          cache: 'npm'

      - name: Install system dependencies (Linux)
        if: runner.os == 'Linux'
        run: |
          # Update package lists
          sudo apt update
          
          # Install core development tools
          sudo apt install -y python3 python3-pip python3-venv

          # Install minimal VS Code dependencies (xvfb-action handles most display setup)
          sudo apt install -y libgbm1 libgtk-3-0 libnss3 xvfb

      - name: Install npm dependencies
        run: npm ci
      
      - name: Install webview dependencies
        run: cd webview-ui && npm ci && cd ..
      
      - name: Compile TypeScript
        run: npm run compile

      - name: Run E2E Test (Ubuntu)
        if: matrix.os == 'ubuntu-latest'
        run: |
          echo "Running E2E test suite..."
          xvfb-run -a npm run test:e2e

      - name: Run E2E Test (macOS)
        if: matrix.os == 'macos-latest'
        run: |
          echo "Running E2E test suite..."
          npm run test:e2e

      - name: Upload test results
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: e2e-test-results
          path: |
            test-results/
            coverage/
            *.log
          retention-days: 30