name: E2E Tests

on:
  workflow_dispatch:
  push:
    branches: [ master, main ]
  pull_request:
    branches: [ master, main ]
  schedule:
    # Run weekly on Sundays at 3 AM UTC
    - cron: '0 3 * * 0'

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  e2e-test:
    runs-on: ubuntu-latest
    name: E2E Tool Installation and ArduPilot Build

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22'
          cache: 'npm'

      - name: Install system dependencies
        run: |
          # Update package lists
          sudo apt update
          
          # Install core development tools
          sudo apt install -y gcc g++ gdb ccache tmux python3 python3-pip
          
          # Install ARM cross-compilation toolchain
          sudo apt install -y gcc-arm-none-eabi gdb-multiarch
          
          # Install optional tools
          sudo apt install -y openocd gdbserver
          
          # Install virtual display for VSCode extension testing
          sudo apt install -y xvfb

      - name: Install Python packages
        run: |
          python3 -m pip install --upgrade pip
          python3 -m pip install pyserial mavproxy

      - name: Verify tool installation
        run: |
          echo "=== Tool Verification ==="
          python3 --version
          gcc --version | head -1
          g++ --version | head -1
          gdb --version | head -1
          arm-none-eabi-gcc --version | head -1
          ccache --version | head -1
          tmux -V
          openocd --version 2>&1 | head -1
          git --version

      - name: Install npm dependencies
        run: npm ci
      
      - name: Install webview dependencies
        run: cd webview-ui && npm ci && cd ..
      
      - name: Compile TypeScript
        run: npm run compile

      - name: Run E2E Test
        run: |
          echo "Running E2E test suite..."
          xvfb-run -a npm run test:e2e

      - name: Upload test results
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: e2e-test-results
          path: |
            test-results/
            coverage/
            *.log
          retention-days: 30